
services:
  rabbitmq:
    image: "rabbitmq:3.7.14-management"

  api:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  worker:
    build: .
    command: celery -A core.worker worker --loglevel=info
    depends_on:
      - rabbitmq